baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Shrink Foo'

[markup]
  defaultMarkdownHandler = "goldmark"

[taxonomies]
tag = "tags"
category = "categories"

[params]
  # Favicon (place your favicon.ico file in the static directory)
  favicon = "/assets/img/favicon.png"
  apple_touch_icon = "/assets/img/apple-touch-icon.png"
  logo = "/assets/img/logo.png"

  # Colors
  primaryColor = "#4d347a"
  hoverColor = "#41227a"
  secondaryColor = "#fc9518"

  # Social links
  [[params.social]]
    icon = "bi bi-facebook"  
    link = "#"              
  [[params.social]]
    icon = "bi bi-whatsapp" 
    link = "#"               
  [[params.social]]
    icon = "bi bi-youtube" 
    link = "#"               
  [[params.social]]
    icon = "bi bi-instagram" 
    link = "#"



[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 2

[[menu.main]]
    identifier = "fun_tuff"
    name = "Fun Tuff"
    url = "/fun-tuff"
    weight = 3

[[menu.main]]
    parent ="fun_tuff"
    identifier = "page_1"
    name = "Page 1"
    url = "/page-1"
    weight = 1

[[menu.main]]
    parent ="fun_tuff"
    identifier = "page_2"
    name = "Page 2"
    url = "/page-2"
    weight = 2

[[menu.main]]
    identifier = "resources"
    name = "Resources"
    url = "/resources"
    weight = 4

[[menu.main]]
    identifier = "training"
    name = "Training"
    url = "/training"
    weight = 5
